name: New github actiontesting 

on: 
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 

jobs:
  build:
    runs-on : nonprod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name : Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
    
      - name: Frontend Compilation (Syntax Check)
        run: |
          cd client
          find . -name "*.js" -exec node --check {} +

      - name: Backend Compilation (Syntax Check)
        run: |
          cd api
          find . -name "*.js" -exec node --check {} +
  
  gitleaks-scan:
    runs-on: nonprod
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Gitleaks Setup
        uses: gitleaks/gitleaks-action@v2

      - name: Gitleaks Scan
        run: |
          gitleaks detect --source ./client --exit-code 1
          gitleaks detect --source ./api --exit-code 1
  
  trivy-scan:
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/trivy-action@0.28.0

      - name: Trivy FS Scan (Source Code)
        run: trivy fs --exit-code 1 --severity CRITICAL,HIGH . --format sarif --output trivy-results.sarif

      - name: Upload Trivy Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.sarif





