name: New github actiontesting 

on: 
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 

jobs:
  build:
    runs-on : nonprod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name : Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
    
      - name: Frontend Compilation (Syntax Check)
        run: |
          cd client
          find . -name "*.js" -exec node --check {} +

      - name: Backend Compilation (Syntax Check)
        run: |
          cd api
          find . -name "*.js" -exec node --check {} +
  
  gitleaks-scan:
    runs-on: nonprod
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gitleaks Scan
        uses: zricethezav/gitleaks-action@v1.3.0
        with:
          args: "--verbose --redact --report-path=gitleaks-report.json --exit-code=1"
        
      
      

